### ISSUE TITLE
jsdom as peerDependency

### ISSUE THREAD

**Issue by JMJustas** [rstacruz/jsdom-global#16]
`jsdom` should be marked as peerDependency because tools like [depcheck](https://github.com/depcheck/depcheck) complain about unused dependency which is required by your lib ;)

**Comment by dsole** [comment]
jsdom-global uses jsdom though. So in my opinion jsdom should be a dependency, not a peer dependency. 
But I certainly agree that devDependencies isn't the right place for jsdom. 

My package would have no need to declare jsdom as a dependency if I've already declared jsdom-global, because my package doesnt use jsdom directly.

**Comment by rstacruz** [comment]
yeah this should be done, yes!

**Comment by rstacruz** [comment]
Done in v3.0.2.
